package com.prongbang.main;

import com.prongbang.format.Converter;
import com.prongbang.utils.DialogUtil;
import com.prongbang.utils.MusicUtil;
import java.awt.Toolkit;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prongbang
 */
public class MusicConverterJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1129941620533453426L;

    private DefaultTableModel model;

    /**
     * Creates new form Music4MatterJFrame
     */
    public MusicConverterJFrame() {
        initComponents();
        setLocationRelativeTo(null);  // this will center your app
        jTablePlaylist.getColumn("#").setPreferredWidth(2);
        jTablePlaylist.getColumn("Songs").setPreferredWidth(350);
        jTablePlaylist.getColumn("Status").setPreferredWidth(30);
        jStartButton.setEnabled(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPathTF = new javax.swing.JTextField();
        jBrowseButton = new javax.swing.JButton();
        jStartButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlaylist = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Music Formatter 1.0.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jBrowseButton.setText("Browse...");
        jBrowseButton.setName(""); // NOI18N
        jBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseButtonActionPerformed(evt);
            }
        });

        jStartButton.setText(" Start ");
        jStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartButtonActionPerformed(evt);
            }
        });

        jTablePlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Songs", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTablePlaylist);

        jLabel1.setText("Source Patch : ");

        jLabel2.setText("From : ");

        jLabelFrom.setText("Mp4");

        jLabel4.setText("to : ");

        jLabelTo.setText("Mp3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFrom)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTo)
                        .addGap(179, 179, 179)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseButton))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPathTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartButton)
                    .addComponent(jLabel2)
                    .addComponent(jLabelFrom)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseButtonActionPerformed

        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Integer opt = j.showSaveDialog(this);

        if (j.getSelectedFile() != null) {
            jPathTF.setText(j.getSelectedFile().getAbsolutePath());

            if (jPathTF.getText() != null && !jPathTF.getText().equals("")) {
                jPathTF.setEditable(false);
                if (addMusicToTableModel(jPathTF.getText())) {
                    jStartButton.setEnabled(true);
                } else {
                    DialogUtil.show(rootPane, "Music Not Found!");
                }
            }
        }

    }//GEN-LAST:event_jBrowseButtonActionPerformed

    private void jStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartButtonActionPerformed

        String from = jLabelFrom.getText().toLowerCase();
        String to = jLabelTo.getText().toLowerCase();
        List<File> playlist = MusicUtil.getPlaylist(jPathTF.getText(), from);
        if (playlist.size() > 0) {
            Converter.getInstance(model).formatter(playlist, from, to);
        } else {
            DialogUtil.show(rootPane, "Formatter Completed!");
        }

    }//GEN-LAST:event_jStartButtonActionPerformed

    public boolean addMusicToTableModel(String path) {
        model = (DefaultTableModel) jTablePlaylist.getModel();
        model.setRowCount(0);
        jTablePlaylist.setRowHeight(25);

        String from = jLabelFrom.getText().toLowerCase();

        int i = 1;
        for (File f : MusicUtil.getPlaylist(path, from)) {
            Object[] rowData = new Object[]{
                String.valueOf(i++),
                f.getName(),
                ""
            };
            model.addRow(rowData);
        }
        return i != 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicConverterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MusicConverterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrowseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JTextField jPathTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jStartButton;
    private javax.swing.JTable jTablePlaylist;
    // End of variables declaration//GEN-END:variables
}
